export const SET_SHOW_LOGOUT = 'SET_SHOW_LOGOUT'

export const SET_CURRENT_ID = 'SET_CURRENT_ID'

export const SET_EMPLOYEE_TYPES = 'SET_EMPLOYEE_TYPES'

export const SET_EMPLOYEE_STATUS = 'SET_EMPLOYEE_STATUS'

export const SET_CURRENT_TYPE = 'SET_CURRENT_TYPE'

export const SET_MENU_ITEMS = 'SET_MENU_ITEMS'

export const SET_MODAL_DATA = 'SET_MODAL_DATA'

export const ADD_NOTIFICATIONS = 'ADD_NOTIFICATIONS'

export const SET_AVAILABLE_EMP_TYPES = 'SET_AVAILABLE_EMP_TYPES'
